apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "provider-postgresql.fullname" . }}
  labels:
    {{- include "provider-postgresql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "provider-postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "provider-postgresql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "provider-postgresql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WEBHOOK_TLS_CERT_DIR
              value: /webhook/tls
          args:
            {{- toYaml .Values.operator.args | nindent 12 }}
          ports:
            - name: webhook
              containerPort: 9443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: webhook
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: webhook
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: webhook-tls
              readOnly: true
              mountPath: /webhook/tls
      volumes:
        - name: webhook-tls
          secret:
            secretName: {{ include "provider-postgresql.fullname" . }}-webhook-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
