---
# Default values for maxscale.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

db1Address: db1.example.com
db2Address: db2.example.com
db3Address: db3.example.com
serviceUser: maxscale
servicePassword: secret
monitorUser: maxscale
monitorPassword: secret

## MaxScale passwords using an existing secret
## The secret needs the keys 'service-password' and 'monitor-password'
# existingSecret: secret

replicaCount: 1

image:
  repository: docker.io/appuio/maxscale
  tag: 2.2.20
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3306
  masteronly:
    type: LoadBalancer
    annotations: {}
  rwsplit:
    type: LoadBalancer
    annotations: {}

resources: {}
# We usually recommend not to specify default resources and to leave
# this as a conscious choice for the user. This also increases chances
# charts run on environments with little resources, such as Minikube.
# If you do want to specify resources, uncomment the following lines,
# adjust them as necessary, and remove the curly braces after
# 'resources:'.
#  requests:
#    cpu: '1'
#    memory: 128Mi
#  limits:
#    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Prometheus Metrics Exporter
metrics:
  enabled: false
  image:
    repository: skord/maxscale_exporter
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}
  # Same as above...
  #  requests:
  #    memory: 16Mi
  #  limits:
  #    memory: 64Mi
