apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "files/*.xml").AsConfig | nindent 2 }}

  {{- (.Files.Glob "files/stardog.properties").AsConfig | nindent 2 }}
    {{- .Values.stardog.config | nindent 4 }}
    {{- if .Values.zookeeper.enabled -}}
    pack.enabled=true
    pack.zookeeper.address={{ template "stardog.zookeeperConnection" . }}
    pack.session.timeout=15s
    {{- if .Values.zookeeper.auth.enabled }}
    pack.zookeeper.auth=$ZOOKEEPER_USERNAME:$ZOOKEEPER_PASSWORD
    {{- end }}
    {{- end }}
