---
baas_operator:
  image: docker.io/appuio/baas:v0.1.1
  ## Allows the specification of additional environment variables
  envVars: |
    - name: BACKUP_IMAGE
      value: docker.io/appuio/wrestic:latest
    # - name: BACKUP_GLOBALACCESSKEYID
    #   valueFrom:
    #     secretKeyRef:
    #       name: global-s3-credentials
    #       key: access-key-id

rbac:
  create: false
