---
# -- Dict with key/values. Each key is the name of the secret.
# Each value may contain an object with `.nameTemplate`, `.type`, `.stringData`, `.data`, `.labels`, `.annotations`.
# If `.nameTemplate` is not given, the key name is used.
# You can pass additional templates to `.stringDataTemplates` and `.nameTemplate`.
# See an example in `values.yaml`.
secrets: {}
# secrets:
#   my-secret-name:
#     nameTemplate: '{{ .Values.fullnameOverride | default .Release.Name }}-suffix' # optional
#     stringData:
#       my-user: example
#       my-file: |
#         [section]
#         config = value
#     stringDataTemplates:
#       my-template: |
#         date={{ now }}
#       my-name: '{{ .Values.secrets.database.name }}'
#     data:
#       my-key: some-base64-encoded-string
#     labels: # optional
#       app: database
#     annotations: # optional
#       my-annotation: a string value
